apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-bdd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-bdd
  template:
    metadata:
      labels:
        app: postgres-bdd
    spec:
      containers:
        - name: postgres
          image: iacontaineregistry.azurecr.io/postgres:latest
          env:
            - name: DB_HOST
              value: postgres
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-bdd
  ports:
    - port: 8080
      targetPort: 8080

